/**
 * Personal Finance Service.
 * personal finance service that manages transactions for users.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface User { 
    id?: number;
    firstName?: string;
    lastName?: string;
    creationDate?: string;
    updateDate?: string;
}

