@startuml

start
:Save bank account dto.;
if (Does the bank account's owner exist?) then (yes)
    :Find bank owner by name.;
else (no)
    :Error: Owner not found.;
    stop
endif
if (Does the bank account exist?) then (yes)
    :Find bank account entity.;
else (no)
    :Create new empty entity.;
endif

if (Are bank account field values valid?) then (yes)
    :Set entity to given values.;
else (no)
    :Error: Invalid bank account values;
    stop
endif

:Write entity to the database.;
stop
@enduml
