openapi: 3.0.0

info:
  title: Personal Finance Service.
  description: personal finance service that manages transactions for users.
  version: 1.0.0

servers:
  - url: http://localhost:8080

paths:
  /users:
    get:
      summary: Returns a page of users.
      responses:
        '200':
          description: A JSON page of users.
          content:
            application/json:
              schema:
                $ref: './resources/Page.yaml'

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: number
        firstName:
          type: string
        lastName:
          type: string
        creationDate:
          type: string
        updateDate:
          type: string
    Users:
      type: array
      items:
        $ref: '#/components/schemas/User'