openapi: 3.0.0

info:
  title: Personal Finance Service.
  description: personal finance service that manages transactions for users.
  version: 1.0.0

servers:
  - url: http://localhost:8080

paths:
  /users:
    $ref: "./paths/users.yaml"
  /users/{userId}:
    $ref: "./paths/user.yaml"
  /users/{userId}/accounts:
    $ref: "./paths/accounts.yaml"
  /users/{userId}/accounts/{accountId}:
    $ref: "./paths/account.yaml"